CREATE DATABASE IF NOT EXISTS CarRental;

USE CarRental;


CREATE TABLE IF NOT EXISTS CLIENTS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	TELEPHONE VARCHAR(20),
	BIRTH_DATE DATE,
	PRIMARY KEY (ID),
	UNIQUE KEY (CPF)
	
);

select * from CLIENTS